//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealStateManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminFee
    {
        public long adminFeeid { get; set; }
        public Nullable<int> adminFeeDefinitionId { get; set; }
        public string adminFeeDescription { get; set; }
        public Nullable<long> contractId { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<decimal> percentageValue { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual adminFeesDefinition adminFeesDefinition { get; set; }
        public virtual contract contract { get; set; }
    }
}
