//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealStateManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminFeesDefinition
    {
        public adminFeesDefinition()
        {
            this.adminFees = new HashSet<adminFee>();
        }
    
        public int adminFeeDefinitionId { get; set; }
        public string description { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<int> percentage { get; set; }
    
        public virtual ICollection<adminFee> adminFees { get; set; }
    }
}
