//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealStateManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        public asset()
        {
            this.checkListAssets = new HashSet<checkListAsset>();
        }
    
        public long assetId { get; set; }
        public Nullable<int> assetTypeId { get; set; }
        public Nullable<long> contractId { get; set; }
        public string brand { get; set; }
        public string serialNo { get; set; }
        public Nullable<decimal> value { get; set; }
        public string description { get; set; }
        public string condition { get; set; }
        public Nullable<System.DateTime> givenOn { get; set; }
        public Nullable<System.DateTime> takenOn { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual assetType assetType { get; set; }
        public virtual contract contract { get; set; }
        public virtual ICollection<checkListAsset> checkListAssets { get; set; }
    }
}
