//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealStateManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assetType
    {
        public assetType()
        {
            this.assets = new HashSet<asset>();
        }
    
        public int assetTypeId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<asset> assets { get; set; }
    }
}
