//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealStateManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class housingUnit
    {
        public housingUnit()
        {
            this.maintenanceRequests = new HashSet<maintenanceRequest>();
        }
    
        public long housingUnitId { get; set; }
        public Nullable<int> housingUnitTypeId { get; set; }
        public Nullable<int> usageTypeId { get; set; }
        public string UnitNumber { get; set; }
        public string name { get; set; }
        public string emirate { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string tawtheeqId { get; set; }
        public string zone { get; set; }
        public string sector { get; set; }
        public string plot { get; set; }
        public string ownerName { get; set; }
        public string areaSize { get; set; }
        public Nullable<long> parent { get; set; }
        public Nullable<int> treeLevel { get; set; }
        public Nullable<bool> vacant { get; set; }
        public Nullable<bool> active { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> subjectToRent { get; set; }
        public Nullable<bool> hasSubUnits { get; set; }
        public string treePath { get; set; }
    
        public virtual housingUnitType housingUnitType { get; set; }
        public virtual usageType usageType { get; set; }
        public virtual ICollection<maintenanceRequest> maintenanceRequests { get; set; }
    }
}
