//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealStateManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenanceInvoice
    {
        public long maintenanceInvoiceId { get; set; }
        public Nullable<long> maintenanceRequestId { get; set; }
        public string invoiceNo { get; set; }
        public Nullable<System.DateTime> invoiceDate { get; set; }
        public Nullable<decimal> invoiceValue { get; set; }
        public string description { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual maintenanceRequest maintenanceRequest { get; set; }
    }
}
