//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealStateManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class realStateDBEntities : DbContext
    {
        public realStateDBEntities()
            : base("name=realStateDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminFee> adminFees { get; set; }
        public virtual DbSet<adminFeesDefinition> adminFeesDefinitions { get; set; }
        public virtual DbSet<asset> assets { get; set; }
        public virtual DbSet<assetType> assetTypes { get; set; }
        public virtual DbSet<checkListAsset> checkListAssets { get; set; }
        public virtual DbSet<checkListReportData> checkListReportDatas { get; set; }
        public virtual DbSet<checkListReportDefinition> checkListReportDefinitions { get; set; }
        public virtual DbSet<checkListReport> checkListReports { get; set; }
        public virtual DbSet<contract> contracts { get; set; }
        public virtual DbSet<contractType> contractTypes { get; set; }
        public virtual DbSet<DM> DMS { get; set; }
        public virtual DbSet<housingUnit> housingUnits { get; set; }
        public virtual DbSet<housingUnitType> housingUnitTypes { get; set; }
        public virtual DbSet<maintenanceInvoice> maintenanceInvoices { get; set; }
        public virtual DbSet<maintenanceRequest> maintenanceRequests { get; set; }
        public virtual DbSet<maintenanceType> maintenanceTypes { get; set; }
        public virtual DbSet<paymeny> paymenys { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<usageType> usageTypes { get; set; }
    }
}
